name: dartkt
description: kotlin extensions for dart
version: 1.0.0
homepage: https://rarnu.xyz

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  convert: ^2.1.1
  crypto: ^2.1.4

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
